### ISSUE TITLE
Problemas con la práctica 2.

### ISSUE THREAD

**Issue by FranciscoNaveros** [JesGor/Proyecto-IV-DAI#2]
Hola.
En el guión de prácticas se especifica lo siguiente:
En la documentación de este hito, que se integrará como el resto en el README.md del proyecto, se explicará por qué se ha elegido el sistema de test y de integración continua.

Además tienes que cumplir 3 objetivos:
3 puntos: Configuración correcta de herramientas de construcción.
5 puntos: Integración continua funcionando.
2 puntos: Tests significativos y/o avance del proyecto en sí más allá de lo básico.

Quiero que me detalles en el README todos los pasos que has seguido para hacer esta práctica y me los justifiques.

En configuración correcta de herramientas de contrucción se refiere a que hagas un makefile (o cualquier otra opción que te parezca) para realizar todas las tareas con una sola orden. Por ejemplo, para pasar los test en local, que sea simplemente hacer make test y que esto llame a mocha test/test.js, python test.py o lo que sea que uses para pasar los test.

Este makefile irá aumentando con cada práctica.

**Comment by JesGor** [comment]
Según lo que pone en el enunciado,  referente al readme, no tenia que poner
los pasos uno por uno de la practica, sino decir que sistema de integracion
continua y de test utilizo y por qué, por eso no los habia puesto.

**Comment by JesGor** [comment]
Listo. Acabo de crear el fichero makefile para la configuración de herramientas de construcción y poder realizar las tareas con una sola orden. También he añadido los pasos que he seguido referentes a la práctica 2, en el apartado de [Desarrollo basado en pruebas](https://github.com/JesGor/Proyecto-IV-DAI#desarrollo-basado-en-pruebas) y en el de [Integración continua](https://github.com/JesGor/Proyecto-IV-DAI#integraci%C3%B3n-continua)
